apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
 containers:
   - name: client
     image: ksreddy4599/fibonacci-worker
     ports:
      - containerPort: 9999